### ISSUE TITLE
Suggestion: Filter memes by rank or karma

### ISSUE THREAD

**Issue by ddugovic** [chand1012/Discord-Quick-Meme#2]
Assuming memes are ranked, maybe by default only return them from the top half of the list (or if not, maybe exclude memes with negative karma)?

https://github.com/chand1012/Discord-Quick-Meme/blob/e82f5df03ac8afe32b844c75af99cc11358310d2/lib.py#L51

**Comment by chand1012** [comment]
Sorry for the slow response, by default it already takes memes from the "hot" section, which usually do not have negative karma, so it really doesn't need to be filtered. 
https://github.com/chand1012/Discord-Quick-Meme/blob/e82f5df03ac8afe32b844c75af99cc11358310d2/lib.py#L25
/
Has anyone had an instance where it does pull a meme (or any other form of media) with negative karma? I wouldn't be surprised if it did that with content from a smaller subreddit but I think with the major ones it shouldn't.

**Comment by ddugovic** [comment]
Sorry, I hadn't received any with negative karma (just low values on smaller subreddits).  But this does address my concern that the bot shouldn't return negative-karma content.
