### ISSUE TITLE
[BUG] Found something wrong with the bot.

### ISSUE THREAD

**Issue by ITDev93** [chand1012/Discord-Quick-Meme#41]
**Describe the bug**
I don't know what it is, just reporting what I got
![20220129_023354](https://user-images.githubusercontent.com/22062468/151635628-d2d0c46f-be03-40ce-a57a-49413527f393.jpg)

**To Reproduce**
!quickmeme subscribe 15m petsareamazing

**Expected behavior**
Auto reddit post every 15 minutes 

**Screenshots**
Already attached in bug description 

**Platform (please complete the following information):**
 - Android 10 - Note20 Ultra 
 - Discord Version 111.6 stable

**Additional context**
None.

**Comment by chand1012** [comment]
Please retry your command and see if the error persists.

**Comment by chand1012** [comment]
No response in 5 months, closing due to staleness.
